Repository google/filament, pull requests merged in 2022-09, with the labels that each got.

#6022 graphvizify should only be implemented on debug builds
  filament/src/fg/PassNode.cpp
  filament/src/fg/details/DependencyGraph.h
  filament/src/fg/details/PassNode.h
Labels: internal

#6028 Fix a "dangling" texture in a SamplerGroup
  filament/src/MaterialInstance.cpp
  filament/src/PostProcessManager.cpp
  filament/src/details/MaterialInstance.cpp
  filament/src/details/MaterialInstance.h
Labels: internal

#6029 In debug builds, verify destroyed textures aren't in sampler groups
  filament/backend/src/metal/MetalContext.h
  filament/backend/src/metal/MetalDriver.mm
Labels: internal

#6030 check that user materials don't exceed their allowed features
  filament/backend/include/backend/DriverEnums.h
  filament/backend/src/metal/MetalDriver.mm
  filament/backend/src/metal/MetalHandles.h
  libs/filamat/include/filamat/MaterialBuilder.h
  libs/filamat/src/Enums.cpp
  libs/filamat/src/MaterialBuilder.cpp
  libs/filamat/src/SamplerBindingMap.cpp
  libs/filamat/src/SamplerBindingMap.h
  libs/filamat/src/sca/GLSLTools.cpp
  libs/utils/include/utils/CString.h
Labels: internal

#6045 gltfio: fix crash when material is unspecified
  libs/gltfio/src/AssetLoader.cpp
Labels: gltf, internal

#6046 gltfio: do not clear out the texture slots too early.
  libs/gltfio/src/FilamentAsset.cpp
  libs/gltfio/src/ResourceLoader.cpp
Labels: web, gltf, internal

#6053 Vk: When the layout requirement change, the pipeline is "dirty".
  filament/backend/src/vulkan/VulkanPipelineCache.cpp
  filament/backend/src/vulkan/VulkanPipelineCache.h
Labels: vulkan, internal

#6052 gltfio: prep step for allowing zero-instance assets
  libs/gltfio/src/AssetLoader.cpp
Labels: gltf, internal

#6054 Vk: do not provide descriptors for unused samplers.
  filament/backend/src/vulkan/VulkanBlitter.cpp
  filament/backend/src/vulkan/VulkanDriver.cpp
  filament/backend/src/vulkan/VulkanPipelineCache.cpp
  filament/backend/src/vulkan/VulkanPipelineCache.h
Labels: vulkan, internal

#6061 fix typo in spotlight attenuation doc
  docs/Filament.md.html
Labels: internal

#6059 gltfio: use BitmaskFlags for sRGB
  libs/gltfio/include/gltfio/TextureProvider.h
  libs/gltfio/src/AssetLoader.cpp
  libs/gltfio/src/DependencyGraph.h
  libs/gltfio/src/FFilamentAsset.h
  libs/gltfio/src/FilamentAsset.cpp
  libs/gltfio/src/Ktx2Provider.cpp
  libs/gltfio/src/ResourceLoader.cpp
  libs/gltfio/src/StbProvider.cpp
Labels: gltf, internal

#6062 Add return case to fix G3 compiler error
  libs/gltfio/src/AssetLoader.cpp
Labels: internal

#6063 Fix FilamentApp multiview mode in gltf_viewer
  filament/include/filament/View.h
  samples/gltf_viewer.cpp
Labels: internal

#6065 gltfio: fix regression when textures are "shared"
  libs/gltfio/include/gltfio/TextureProvider.h
  libs/gltfio/src/FFilamentAsset.h
  libs/gltfio/src/FilamentAsset.cpp
  libs/gltfio/src/ResourceLoader.cpp
Labels: internal

#6066 bump max sampler count to 62
  filament/backend/include/backend/DriverEnums.h
  filament/backend/src/opengl/OpenGLContext.cpp
  filament/backend/src/opengl/OpenGLContext.h
  filament/backend/src/vulkan/VulkanPipelineCache.cpp
  filament/backend/src/vulkan/VulkanPipelineCache.h
  filament/src/MaterialParser.cpp
  libs/filabridge/include/private/filament/SamplerBindingsInfo.h
  libs/filabridge/include/private/filament/SamplerInterfaceBlock.h
  libs/filamat/src/SamplerBindingMap.cpp
  libs/utils/include/utils/bitset.h
Labels: internal

#6069 Vulkan samplers: fit incorrect bitset logic.
  filament/backend/src/vulkan/VulkanPipelineCache.cpp
  filament/backend/src/vulkan/VulkanPipelineCache.h
Labels: internal

#6073 Vk getFeatureLevel() should use `maxPerStageDescriptorSamplers`
  filament/backend/src/vulkan/VulkanDriver.cpp
Labels: internal

#6078 Upgrade AGP and dependencies including plugins
  BUILDING.md
  android/build.gradle
  android/filamat-android/src/main/AndroidManifest.xml
  android/filament-android/src/main/AndroidManifest.xml
  android/filament-utils-android/src/main/AndroidManifest.xml
  android/filament-utils-android/src/main/java/com/google/android/filament/utils/ModelViewer.kt
  android/gltfio-android/src/main/AndroidManifest.xml
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/samples/sample-gltf-viewer/src/main/AndroidManifest.xml
  android/samples/sample-hello-camera/src/main/AndroidManifest.xml
  android/samples/sample-hello-triangle/src/main/AndroidManifest.xml
  android/samples/sample-image-based-lighting/src/main/AndroidManifest.xml
  android/samples/sample-lit-cube/src/main/AndroidManifest.xml
  android/samples/sample-live-wallpaper/src/main/AndroidManifest.xml
  android/samples/sample-material-builder/src/main/AndroidManifest.xml
  android/samples/sample-multi-view/src/main/AndroidManifest.xml
  android/samples/sample-page-curl/src/main/AndroidManifest.xml
  android/samples/sample-stream-test/src/main/AndroidManifest.xml
  android/samples/sample-texture-view/src/main/AndroidManifest.xml
  android/samples/sample-textured-object/src/main/AndroidManifest.xml
  android/samples/sample-transparent-view/src/main/AndroidManifest.xml
  build/android/ndk.version
Labels: internal

#6085 matinfo: fix feature level print output
  libs/matdbg/src/TextWriter.cpp
Labels: internal

#6086 cleanup: move `string` uses over to `string_view`
  libs/filamat/include/filamat/MaterialBuilder.h
  libs/filamat/src/sca/ASTHelpers.cpp
  libs/filamat/src/sca/ASTHelpers.h
  libs/filamat/src/sca/GLSLTools.cpp
  libs/filamat/src/sca/GLSLTools.h
  libs/filamat/tests/test_filamat.cpp
Labels: internal

#6082 use ES3.1 headers
  filament/backend/src/opengl/gl_headers.h
Labels: internal

#6087 Add `MetalRingBuffer` for future argument buffer management
  filament/backend/src/metal/MetalBuffer.h
Labels: internal

#6088 fix android debug build
  filament/backend/src/opengl/gl_headers.h
Labels: internal

#6089 attempt to fix android build again
  filament/backend/src/opengl/gl_headers.h
  filament/src/details/Scene.cpp
Labels: internal

#6095 fix (again) the box-frustum intersection
  filament/src/ShadowMap.cpp
Labels: internal

#6099 Update cgltf to version 1.13
  third_party/cgltf/README.md
  third_party/cgltf/cgltf.h
  third_party/cgltf/cgltf_write.h
  third_party/cgltf/test/CMakeLists.txt
  third_party/cgltf/test/test_all.py
  third_party/cgltf/test/test_write_glb.cpp
Labels: internal

#6097 Wayland FilamentApp
  libs/filamentapp/src/FilamentApp.cpp
  libs/filamentapp/src/NativeWindowHelperLinux.cpp
Labels: internal

#6117 Fix generic/Mutex.h not installed on Linux
  libs/utils/CMakeLists.txt
Labels: internal

#6118 don't attempt to use more texture units than present
  filament/backend/src/opengl/OpenGLContext.h
  filament/backend/src/opengl/OpenGLDriver.cpp
Labels: internal

#6108 reduce setParameter(texture) calls
  filament/src/PostProcessManager.cpp
Labels: internal

#6125 Fixes for 1.27.2 release
  android/filamat-android/src/main/AndroidManifest.xml
  android/filament-android/src/main/AndroidManifest.xml
  android/filament-utils-android/src/main/AndroidManifest.xml
  filament/backend/src/opengl/OpenGLContext.h
Labels: internal

#6122 Fix a crash by setting not exist material parameters on ubershader
  RELEASE_NOTES.md
  libs/gltfio/src/ArchiveCache.cpp
  libs/gltfio/src/ArchiveCache.h
  libs/gltfio/src/UbershaderProvider.cpp
Labels: internal

#6127 fix artifacts EVSM shadows and allow 32 bits texture and full precision EVSMs as options.
  RELEASE_NOTES.md
  android/filament-android/src/main/cpp/LightManager.cpp
  android/filament-android/src/main/cpp/View.cpp
  android/filament-android/src/main/java/com/google/android/filament/LightManager.java
  android/filament-android/src/main/java/com/google/android/filament/View.java
  filament/include/filament/LightManager.h
  filament/include/filament/Options.h
  filament/src/PerViewUniforms.cpp
  filament/src/PerViewUniforms.h
  filament/src/RendererUtils.cpp
  filament/src/ShadowMapManager.cpp
  filament/src/ShadowMapManager.h
  filament/src/details/View.cpp
  filament/src/details/View.h
  libs/filabridge/include/private/filament/UibStructs.h
  libs/viewer/src/Settings.cpp
  libs/viewer/src/Settings_generated.cpp
  libs/viewer/src/ViewerGui.cpp
  shaders/src/common_types.glsl
  shaders/src/depth_main.fs
  shaders/src/main.vs
  shaders/src/shadowing.fs
  web/filament-js/extensions_generated.js
  web/filament-js/filament.d.ts
  web/filament-js/jsbindings_generated.cpp
Labels: internal

#6137 fix shadowing when the scene is outside the "shadow" view frustum
  filament/src/ShadowMap.cpp
  filament/src/ShadowMapManager.cpp
  filament/src/details/View.cpp
Labels: internal
