Repository google/filament, pull requests merged in 2023-12, with the labels that each got.

#7404 fix jni Scene.getEntities
  android/filament-android/src/main/cpp/EntityManager.cpp
  android/filament-android/src/main/cpp/MaterialInstance.cpp
  android/filament-android/src/main/cpp/Scene.cpp
Labels: internal

#7407 material depth variant caching should only happen for surface materials
  filament/src/details/Material.cpp
Labels: internal

#7410 Fix typo in getStereoscopicOptions Java
  android/filament-android/src/main/java/com/google/android/filament/View.java
Labels: internal

#7333 Improve blitting APIs
  android/filament-android/src/main/java/com/google/android/filament/Texture.java
  filament/backend/include/backend/DriverEnums.h
  filament/backend/include/private/backend/DriverAPI.inc
  filament/backend/src/metal/MetalBlitter.h
  filament/backend/src/metal/MetalBlitter.mm
  filament/backend/src/metal/MetalDriver.mm
  filament/backend/src/metal/MetalHandles.mm
  filament/backend/src/noop/NoopDriver.cpp
  filament/backend/src/opengl/OpenGLDriver.cpp
  filament/backend/src/ostream.cpp
  filament/backend/src/vulkan/VulkanBlitter.cpp
  filament/backend/src/vulkan/VulkanBlitter.h
  filament/backend/src/vulkan/VulkanDriver.cpp
  filament/backend/test/test_Blit.cpp
  filament/include/filament/Texture.h
  filament/src/PostProcessManager.cpp
  filament/src/PostProcessManager.h
  filament/src/RendererUtils.cpp
  filament/src/details/Renderer.cpp
  filament/src/details/Texture.cpp
  filament/src/fg/FrameGraph.cpp
  web/filament-js/jsenums.cpp
Labels: internal

#7416 spirv-headers: fix failed headers check
  third_party/spirv-headers/CMakeLists.txt
  third_party/spirv-headers/filament-specific-changes.patch
  third_party/spirv-tools/.github/workflows/wasm.yml
  third_party/spirv-tools/.gitignore
  third_party/spirv-tools/filament-update.sh
Labels: internal

#7408 Added an option to shorten compile time in Visual Studio
  CMakeLists.txt
Labels: windows, build, internal

#7419 Fixed feature level 0 material build rules
  filament/CMakeLists.txt
Labels: internal

#7418 Dynamic "Material constants" support
  android/filament-android/src/main/java/com/google/android/filament/View.java
  docs/remote/filament.js
  docs/remote/filament.wasm
  docs/webgl/filament.js
  docs/webgl/filament.wasm
  docs/webgl/parquet.filamat
  docs/webgl/plastic.filamat
  docs/webgl/reference.html
  docs/webgl/textured.filamat
  docs/webgl/triangle.filamat
  filament/backend/src/opengl/OpenGLDriver.cpp
  filament/backend/src/opengl/ShaderCompilerService.cpp
  filament/include/filament/Options.h
  filament/src/PostProcessManager.cpp
  filament/src/PostProcessManager.h
  filament/src/details/Engine.cpp
  filament/src/details/Material.cpp
  filament/src/details/Material.h
  filament/src/details/Renderer.cpp
  filament/src/materials/antiAliasing/taa.mat
  libs/filabridge/include/private/filament/EngineEnums.h
  libs/utils/include/utils/CString.h
  libs/viewer/src/Settings_generated.cpp
  libs/viewer/src/Settings_generated.h
  libs/viewer/src/ViewerGui.cpp
  web/filament-js/extensions_generated.js
  web/filament-js/filament.d.ts
  web/filament-js/jsbindings_generated.cpp
  web/filament-js/jsenums_generated.cpp
Labels: internal

#7423 Update dependencies to latest
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: internal

#7420 Allow post-process materials to update the vertex position
  shaders/src/post_process.vs
  shaders/src/post_process_getters.vs
  shaders/src/post_process_inputs.vs
Labels: internal

#7421 fix framegraph clear flags for imported targets
  filament/backend/src/ostream.cpp
  filament/src/fg/PassNode.cpp
Labels: internal

#7422 make a few PostProcessManager methods "package" public
  filament/src/PostProcessManager.h
Labels: internal

#7425 fix per-light shadow "caster" flag update
  filament/src/ShadowMapManager.cpp
  filament/src/details/View.cpp
Labels: internal

#7426 fix getUserWorldFromWorldMatrix() during the shadow passes
  filament/src/PerViewUniforms.cpp
  filament/src/ShadowMapManager.cpp
  filament/src/details/Camera.cpp
  filament/src/details/Camera.h
Labels: internal

#7428 Fix UiHelper
  android/filament-android/src/main/java/com/google/android/filament/android/UiHelper.java
Labels: internal

#7429 fix android build
  libs/matdbg/src/ApiHandler.cpp
  libs/matdbg/src/ApiHandler.h
Labels: build, internal

#7430 fix TAA on mobile devices.
  filament/src/materials/antiAliasing/taa.mat
Labels: internal

#7434 Assert non-null texture in setTextureData
  filament/backend/src/opengl/OpenGLDriver.cpp
Labels: internal

#7436 don't use eglGetProcAddress on emscripten
  docs/remote/filament.js
  docs/remote/filament.wasm
  docs/webgl/filament.js
  docs/webgl/filament.wasm
  docs/webgl/parquet.filamat
  docs/webgl/plastic.filamat
  docs/webgl/textured.filamat
  docs/webgl/triangle.filamat
  filament/backend/src/opengl/OpenGLContext.cpp
  filament/backend/src/opengl/OpenGLDriver.cpp
  filament/backend/src/opengl/gl_headers.cpp
  filament/backend/src/opengl/gl_headers.h
Labels: internal

#7435 add `-fno-limit-debug-info` to android debug builds
  CMakeLists.txt
Labels: internal

#7440 Make`applyMaterialVariant` Method Public in FilamentInstance Class
  android/gltfio-android/src/main/java/com/google/android/filament/gltfio/FilamentInstance.java
Labels: internal

#7441 TAA improvements
  android/filament-android/src/main/java/com/google/android/filament/View.java
  filament/include/filament/Options.h
  filament/src/PostProcessManager.cpp
  filament/src/PostProcessManager.h
  filament/src/details/Renderer.cpp
  filament/src/details/View.cpp
  filament/src/details/View.h
  filament/src/materials/antiAliasing/taa.mat
  libs/viewer/src/Settings_generated.cpp
  libs/viewer/src/Settings_generated.h
  libs/viewer/src/ViewerGui.cpp
  web/filament-js/extensions_generated.js
  web/filament-js/filament.d.ts
  web/filament-js/jsbindings_generated.cpp
  web/filament-js/jsenums_generated.cpp
Labels: internal

#7457 Fix a couple race conditions in Metal backend
  CMakeLists.txt
  filament/backend/src/metal/MetalBufferPool.h
  filament/backend/src/metal/MetalContext.h
Labels: internal
